# problem 2
# Write a program that calculates the profit generated by a movie theatre for different ticket classes.
# 
# For VIP tickets, the profit is 30% of the ticket price + Rs120 for every ticket sold.
# For General tickets, the profit is 20% of the ticket price + Rs80 for every ticket sold.
# For Matinee show tickets, the profit is a flat 15% of the ticket price.
# Input: Ticket price and number of tickets sold for each ticket class.
# Output: Calculate and print the total revenue generated by the theatre in a day.
# 
# VIP -> profit 30% of ticket price + Rs120 for every ticket sold.
# General -> profit 20% of ticket price + Rs80 for every ticket sold.
# Matinee -> profit 15% of the ticket price.
# 

# build the profit calculation function()
def profitCal(movie_class,ticket_price):
    if(movie_class=="vip"):
        ticket_price = (ticket_price*30/100) + ticket_price
    elif(movie_class=="general"):
        ticket_price = (ticket_price*20/100) + ticket_price
    elif(movie_class=="matinee"):
        ticket_price = (ticket_price*15/100) + ticket_price
    return ticket_price

# build total collection function()
def totalCollection():
    # print greeting
    print("Wellcome!, to Theatre revenue ")

    # get vip ticket price
    vip_ticket_price = float(input("Enter Vip ticket price : "))
    # get no of vip ticket sold
    no_of_vticket =  int(input("Enter no of Vip ticket sold : "))
    # get general ticket price
    general_ticket_price = float(input("Enter General ticket price : "))
    # get no of general ticket sold
    no_of_gticket =  int(input("Enter no of General ticket sold : "))
    # get matinee ticket price
    matinee_ticket_price = float(input("Enter Matinee show ticket price : "))
    # get no of matinee ticket sold
    no_of_mticket =  int(input("Enter no of Matinee show ticket sold : "))

    # assign total collection initialy 0
    total_collection = 0

    # find total vip ticket price with profit
    total_collection = total_collection + (profitCal("vip",vip_ticket_price)*no_of_vticket)
    # find total general ticket price add to vip ticket price with profit
    total_collection = total_collection + (profitCal("general",general_ticket_price)*no_of_gticket)
    # find total matinee ticket price add with vip and general price with profit
    total_collection = total_collection + (profitCal("matinee",matinee_ticket_price)*no_of_mticket)

    # return the total collection
    return total_collection

# call total colletion function()
total_revenue = totalCollection()
# print total revenue
print("Total revenue of this day is :",total_revenue)

